# Generated by Django 4.2.17 on 2025-11-09 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位标题')),
                ('category', models.CharField(choices=[('tutoring', '家教辅导'), ('service', '服务类'), ('promotion', '推广宣传'), ('event', '活动助理'), ('tech', '技术类'), ('other', '其他')], max_length=20, verbose_name='职位类别')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='薪资')),
                ('salary_type', models.CharField(choices=[('hourly', '时薪'), ('daily', '日薪'), ('total', '总计')], default='hourly', max_length=10, verbose_name='薪资类型')),
                ('location', models.CharField(max_length=200, verbose_name='工作地点')),
                ('duration', models.CharField(help_text='例如：每天2小时，共5天', max_length=100, verbose_name='工作时长')),
                ('positions', models.IntegerField(default=1, verbose_name='招聘人数')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('open', '招募中'), ('closed', '已结束')], default='open', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '兼职任务',
                'verbose_name_plural': '兼职任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='申请留言')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申请者')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='兼职任务')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
